spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

cors:
  allowed-origins:
    - ${FRONTEND_URL}

oauth2:
  redirect-uri: ${FRONTEND_URL}/oauth2/callback

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      show-components: always

logging:
  level:
    root: INFO
    com.soaengry.geekyard: DEBUG
