spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    enabled: false

cors:
  allowed-origins:
    - ${FRONTEND_URL}

oauth2:
  redirect-uri: ${FRONTEND_URL}/oauth2/callback

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: WARN
    com.soaengry.geekyard: INFO
